// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int32  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UsersProfile struct {
	ID        int32          `json:"id"`
	UsersID   int32          `json:"users_id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Balance   pgtype.Numeric `json:"balance"`
}
